use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::{
    collections::BTreeMap,
    sync::{
        atomic::{AtomicU64, Ordering},
        Arc, OnceLock, RwLock,
    },
};

#[derive(Debug, Clone, Copy, Serialize)]
#[serde(rename_all = "camelCase")]
pub enum ParameterKind {
    Bool,
    Number,
    Select,
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ParameterDefinition {
    pub id: String,
    pub legacy_id: String,
    pub label: String,
    pub group: String,
    pub kind: ParameterKind,
    pub default: Value,
    pub min: Option<f64>,
    pub max: Option<f64>,
    pub step: Option<f64>,
    pub options: Vec<String>,
    pub implemented: bool,
    pub milestone: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ParameterSnapshot {
    pub revision: u64,
    pub values: BTreeMap<String, Value>,
}

impl ParameterSnapshot {
    pub fn number(&self, id: &str, fallback: f64) -> f64 {
        self.values.get(id).and_then(Value::as_f64).unwrap_or(fallback)
    }

    pub fn bool_value(&self, id: &str, fallback: bool) -> bool {
        self.values.get(id).and_then(Value::as_bool).unwrap_or(fallback)
    }

    pub fn text<'a>(&'a self, id: &str, fallback: &'a str) -> &'a str {
        self.values.get(id).and_then(Value::as_str).unwrap_or(fallback)
    }
}

#[derive(Clone)]
pub struct ParameterStore {
    values: Arc<RwLock<BTreeMap<String, Value>>>,
    revision: Arc<AtomicU64>,
}

impl ParameterStore {
    pub fn new() -> Self {
        let values = definitions()
            .iter()
            .map(|definition| (definition.id.clone(), definition.default.clone()))
            .collect();
        Self {
            values: Arc::new(RwLock::new(values)),
            revision: Arc::new(AtomicU64::new(1)),
        }
    }

    pub fn revision(&self) -> u64 {
        self.revision.load(Ordering::Acquire)
    }

    pub fn snapshot(&self) -> ParameterSnapshot {
        ParameterSnapshot {
            revision: self.revision(),
            values: self.values.read().expect("parameter state poisoned").clone(),
        }
    }

    pub fn set(&self, id_or_legacy: &str, value: Value) -> Result<u64, String> {
        let definition = find_definition(id_or_legacy)
            .ok_or_else(|| format!("unknown Huff parameter: {id_or_legacy}"))?;
        let value = validate_value(definition, value)?;
        let mut state = self.values.write().map_err(|_| "parameter state poisoned".to_string())?;
        state.insert(definition.id.clone(), value);
        Ok(self.revision.fetch_add(1, Ordering::AcqRel) + 1)
    }

    pub fn set_many(&self, updates: BTreeMap<String, Value>) -> Result<u64, String> {
        let mut validated = Vec::with_capacity(updates.len());
        for (id, value) in updates {
            let definition = find_definition(&id)
                .ok_or_else(|| format!("unknown Huff parameter: {id}"))?;
            validated.push((definition.id.clone(), validate_value(definition, value)?));
        }
        let mut state = self.values.write().map_err(|_| "parameter state poisoned".to_string())?;
        for (id, value) in validated {
            state.insert(id, value);
        }
        Ok(self.revision.fetch_add(1, Ordering::AcqRel) + 1)
    }

    pub fn reset(&self) -> u64 {
        let mut state = self.values.write().expect("parameter state poisoned");
        state.clear();
        for definition in definitions() {
            state.insert(definition.id.clone(), definition.default.clone());
        }
        self.revision.fetch_add(1, Ordering::AcqRel) + 1
    }

    pub fn value(&self, id_or_legacy: &str) -> Option<Value> {
        let definition = find_definition(id_or_legacy)?;
        self.values
            .read()
            .ok()
            .and_then(|state| state.get(&definition.id).cloned())
    }
}

pub fn canonicalize_parameter_value(
    id_or_legacy: &str,
    value: Value,
) -> Result<(String, Value), String> {
    let definition = find_definition(id_or_legacy)
        .ok_or_else(|| format!("unknown Huff parameter: {id_or_legacy}"))?;
    Ok((definition.id.clone(), validate_value(definition, value)?))
}

fn validate_value(definition: &ParameterDefinition, value: Value) -> Result<Value, String> {
    match definition.kind {
        ParameterKind::Bool => value
            .as_bool()
            .map(Value::Bool)
            .ok_or_else(|| format!("{} expects a boolean", definition.id)),
        ParameterKind::Number => {
            let number = value
                .as_f64()
                .ok_or_else(|| format!("{} expects a number", definition.id))?;
            if !number.is_finite() {
                return Err(format!("{} must be finite", definition.id));
            }
            let number = number
                .max(definition.min.unwrap_or(f64::NEG_INFINITY))
                .min(definition.max.unwrap_or(f64::INFINITY));
            serde_json::Number::from_f64(number)
                .map(Value::Number)
                .ok_or_else(|| format!("{} could not be represented", definition.id))
        }
        ParameterKind::Select => {
            let selected = value
                .as_str()
                .ok_or_else(|| format!("{} expects a string", definition.id))?;
            if !definition.options.iter().any(|option| option == selected) {
                return Err(format!(
                    "{} does not accept {selected:?}; expected one of {:?}",
                    definition.id, definition.options
                ));
            }
            Ok(Value::String(selected.into()))
        }
    }
}

pub fn find_definition(id_or_legacy: &str) -> Option<&'static ParameterDefinition> {
    definitions()
        .iter()
        .find(|definition| definition.id == id_or_legacy || definition.legacy_id == id_or_legacy)
}

pub fn definitions() -> &'static Vec<ParameterDefinition> {
    static DEFINITIONS: OnceLock<Vec<ParameterDefinition>> = OnceLock::new();
    DEFINITIONS.get_or_init(|| vec![
        ParameterDefinition {
            id: "source.base_enabled".into(),
            legacy_id: "baseOn".into(),
            label: "BASE ON".into(),
            group: "Source".into(),
            kind: ParameterKind::Bool,
            default: serde_json::Value::Bool(true),
            min: None,
            max: None,
            step: None,
            options: Vec::new(),
            implemented: true,
            milestone: "02".into(),
        },
        ParameterDefinition {
            id: "source.base_mix".into(),
            legacy_id: "baseMix".into(),
            label: "BASE MIX".into(),
            group: "Source".into(),
            kind: ParameterKind::Number,
            default: serde_json::json!(1),
            min: Some(0.0),
            max: Some(1.0),
            step: Some(0.05),
            options: Vec::new(),
            implemented: true,
            milestone: "02".into(),
        },
        ParameterDefinition {
            id: "source.background".into(),
            legacy_id: "bgMode".into(),
            label: "BG MODE".into(),
            group: "Source".into(),
            kind: ParameterKind::Select,
            default: serde_json::Value::String("black".into()),
            min: None,
            max: None,
            step: None,
            options: vec!["black".into(), "green".into(), "blue".into(), "white".into()],
            implemented: true,
            milestone: "02".into(),
        },
        ParameterDefinition {
            id: "source.seed_on_load".into(),
            legacy_id: "seedOnLoad".into(),
            label: "SEED ON LOAD".into(),
            group: "Source".into(),
            kind: ParameterKind::Bool,
            default: serde_json::Value::Bool(true),
            min: None,
            max: None,
            step: None,
            options: Vec::new(),
            implemented: false,
            milestone: "future".into(),
        },
        ParameterDefinition {
            id: "source.seed".into(),
            legacy_id: "seed".into(),
            label: "SEED".into(),
            group: "Source".into(),
            kind: ParameterKind::Number,
            default: serde_json::json!(912831),
            min: None,
            max: None,
            step: Some(1.0),
            options: Vec::new(),
            implemented: true,
            milestone: "04".into(),
        },
        ParameterDefinition {
            id: "render.quality".into(),
            legacy_id: "quality".into(),
            label: "QUALITY".into(),
            group: "Source".into(),
            kind: ParameterKind::Number,
            default: serde_json::json!(1),
            min: Some(0.0),
            max: Some(3.0),
            step: Some(0.05),
            options: Vec::new(),
            implemented: true,
            milestone: "03".into(),
        },
        ParameterDefinition {
            id: "render.resolution_mode".into(),
            legacy_id: "renderResolution".into(),
            label: "RENDER RESOLUTION".into(),
            group: "Source".into(),
            kind: ParameterKind::Select,
            default: serde_json::Value::String("match".into()),
            min: None,
            max: None,
            step: None,
            options: vec!["match".into(), "640x360".into(), "960x540".into(), "1280x720".into(), "1920x1080".into(), "custom".into()],
            implemented: true,
            milestone: "02".into(),
        },
        ParameterDefinition {
            id: "color.brightness".into(),
            legacy_id: "brightness".into(),
            label: "BRIGHTNESS".into(),
            group: "Source".into(),
            kind: ParameterKind::Number,
            default: serde_json::json!(1),
            min: Some(0.0),
            max: Some(2.0),
            step: Some(0.01),
            options: Vec::new(),
            implemented: true,
            milestone: "02".into(),
        },
        ParameterDefinition {
            id: "color.contrast".into(),
            legacy_id: "contrast".into(),
            label: "CONTRAST".into(),
            group: "Source".into(),
            kind: ParameterKind::Number,
            default: serde_json::json!(1),
            min: Some(0.0),
            max: Some(2.0),
            step: Some(0.01),
            options: Vec::new(),
            implemented: true,
            milestone: "02".into(),
        },
        ParameterDefinition {
            id: "render.custom_width".into(),
            legacy_id: "renderCustomW".into(),
            label: "RENDER CUSTOM W".into(),
            group: "Source".into(),
            kind: ParameterKind::Number,
            default: serde_json::json!(1280),
            min: Some(160.0),
            max: Some(3840.0),
            step: Some(1.0),
            options: Vec::new(),
            implemented: true,
            milestone: "02".into(),
        },
        ParameterDefinition {
            id: "render.custom_height".into(),
            legacy_id: "renderCustomH".into(),
            label: "RENDER CUSTOM H".into(),
            group: "Source".into(),
            kind: ParameterKind::Number,
            default: serde_json::json!(720),
            min: Some(160.0),
            max: Some(2160.0),
            step: Some(1.0),
            options: Vec::new(),
            implemented: true,
            milestone: "02".into(),
        },
        ParameterDefinition {
            id: "history.preset".into(),
            legacy_id: "historyPreset".into(),
            label: "HISTORY PRESET".into(),
            group: "Frame History".into(),
            kind: ParameterKind::Select,
            default: serde_json::Value::String("maximum".into()),
            min: None,
            max: None,
            step: None,
            options: vec!["maximum".into(), "balanced".into(), "performance".into(), "custom".into()],
            implemented: true,
            milestone: "02".into(),
        },
        ParameterDefinition {
            id: "history.resolution".into(),
            legacy_id: "historyResolution".into(),
            label: "HISTORY RESOLUTION".into(),
            group: "Frame History".into(),
            kind: ParameterKind::Select,
            default: serde_json::Value::String("full".into()),
            min: None,
            max: None,
            step: None,
            options: vec!["full".into(), "75".into(), "50".into(), "25".into(), "custom".into()],
            implemented: true,
            milestone: "02".into(),
        },
        ParameterDefinition {
            id: "history.custom_width".into(),
            legacy_id: "historyCustomW".into(),
            label: "HISTORY CUSTOM W".into(),
            group: "Frame History".into(),
            kind: ParameterKind::Number,
            default: serde_json::json!(960),
            min: Some(64.0),
            max: Some(3840.0),
            step: Some(1.0),
            options: Vec::new(),
            implemented: true,
            milestone: "02".into(),
        },
        ParameterDefinition {
            id: "history.custom_height".into(),
            legacy_id: "historyCustomH".into(),
            label: "HISTORY CUSTOM H".into(),
            group: "Frame History".into(),
            kind: ParameterKind::Number,
            default: serde_json::json!(540),
            min: Some(64.0),
            max: Some(2160.0),
            step: Some(1.0),
            options: Vec::new(),
            implemented: true,
            milestone: "02".into(),
        },
        ParameterDefinition {
            id: "history.capture_rate".into(),
            legacy_id: "historyCaptureRate".into(),
            label: "HISTORY CAPTURE RATE".into(),
            group: "Frame History".into(),
            kind: ParameterKind::Select,
            default: serde_json::Value::String("every".into()),
            min: None,
            max: None,
            step: None,
            options: vec!["every".into(), "30".into(), "24".into(), "15".into(), "10".into()],
            implemented: true,
            milestone: "02".into(),
        },
        ParameterDefinition {
            id: "history.sampling".into(),
            legacy_id: "historySampling".into(),
            label: "HISTORY SAMPLING".into(),
            group: "Frame History".into(),
            kind: ParameterKind::Select,
            default: serde_json::Value::String("smooth".into()),
            min: None,
            max: None,
            step: None,
            options: vec!["smooth".into(), "crisp".into()],
            implemented: true,
            milestone: "02".into(),
        },
        ParameterDefinition {
            id: "feedback.amount".into(),
            legacy_id: "feedback".into(),
            label: "FEEDBACK".into(),
            group: "Feedback".into(),
            kind: ParameterKind::Number,
            default: serde_json::json!(0.6),
            min: Some(0.0),
            max: Some(3.0),
            step: Some(0.05),
            options: Vec::new(),
            implemented: true,
            milestone: "02".into(),
        },
        ParameterDefinition {
            id: "feedback.persistence".into(),
            legacy_id: "persistence".into(),
            label: "PERSISTENCE".into(),
            group: "Feedback".into(),
            kind: ParameterKind::Number,
            default: serde_json::json!(0.7),
            min: Some(0.0),
            max: Some(10.0),
            step: Some(0.05),
            options: Vec::new(),
            implemented: true,
            milestone: "02".into(),
        },
        ParameterDefinition {
            id: "feedback.translate_x".into(),
            legacy_id: "fbX".into(),
            label: "FB X".into(),
            group: "Feedback".into(),
            kind: ParameterKind::Number,
            default: serde_json::json!(1),
            min: Some(-1.0),
            max: Some(1.0),
            step: Some(0.001),
            options: Vec::new(),
            implemented: true,
            milestone: "02".into(),
        },
        ParameterDefinition {
            id: "feedback.translate_y".into(),
            legacy_id: "fbY".into(),
            label: "FB Y".into(),
            group: "Feedback".into(),
            kind: ParameterKind::Number,
            default: serde_json::json!(1),
            min: Some(-1.0),
            max: Some(1.0),
            step: Some(0.001),
            options: Vec::new(),
            implemented: true,
            milestone: "02".into(),
        },
        ParameterDefinition {
            id: "feedback.scale".into(),
            legacy_id: "fbZ".into(),
            label: "FB Z".into(),
            group: "Feedback".into(),
            kind: ParameterKind::Number,
            default: serde_json::json!(1),
            min: Some(0.98),
            max: Some(1.03),
            step: Some(0.005),
            options: Vec::new(),
            implemented: true,
            milestone: "02".into(),
        },
        ParameterDefinition {
            id: "feedback.rotation".into(),
            legacy_id: "fbTheta".into(),
            label: "FB THETA".into(),
            group: "Feedback".into(),
            kind: ParameterKind::Number,
            default: serde_json::json!(0.01),
            min: Some(-2.0),
            max: Some(2.0),
            step: Some(0.005),
            options: Vec::new(),
            implemented: true,
            milestone: "02".into(),
        },
        ParameterDefinition {
            id: "glitch.corrupt_on".into(),
            legacy_id: "corruptOn".into(),
            label: "CORRUPT ON".into(),
            group: "Glitch".into(),
            kind: ParameterKind::Bool,
            default: serde_json::Value::Bool(false),
            min: None,
            max: None,
            step: None,
            options: Vec::new(),
            implemented: true,
            milestone: "03".into(),
        },
        ParameterDefinition {
            id: "glitch.depth".into(),
            legacy_id: "depth".into(),
            label: "DEPTH".into(),
            group: "Glitch".into(),
            kind: ParameterKind::Number,
            default: serde_json::json!(0.5),
            min: Some(0.0),
            max: Some(0.5),
            step: Some(0.01),
            options: Vec::new(),
            implemented: true,
            milestone: "03".into(),
        },
        ParameterDefinition {
            id: "glitch.depth_scatter".into(),
            legacy_id: "depthScatter".into(),
            label: "DEPTH SCATTER".into(),
            group: "Glitch".into(),
            kind: ParameterKind::Number,
            default: serde_json::json!(1),
            min: Some(0.0),
            max: Some(1.0),
            step: Some(0.01),
            options: Vec::new(),
            implemented: true,
            milestone: "04".into(),
        },
        ParameterDefinition {
            id: "glitch.corrupt".into(),
            legacy_id: "corrupt".into(),
            label: "CORRUPT".into(),
            group: "Glitch".into(),
            kind: ParameterKind::Number,
            default: serde_json::json!(0.3),
            min: Some(0.0),
            max: Some(7.0),
            step: Some(0.01),
            options: Vec::new(),
            implemented: true,
            milestone: "03".into(),
        },
        ParameterDefinition {
            id: "glitch.corrupt_drift".into(),
            legacy_id: "corruptDrift".into(),
            label: "CORRUPT DRIFT".into(),
            group: "Glitch".into(),
            kind: ParameterKind::Number,
            default: serde_json::json!(0),
            min: Some(0.0),
            max: Some(1.0),
            step: Some(0.01),
            options: Vec::new(),
            implemented: true,
            milestone: "04".into(),
        },
        ParameterDefinition {
            id: "glitch.block".into(),
            legacy_id: "block".into(),
            label: "BLOCK".into(),
            group: "Glitch".into(),
            kind: ParameterKind::Number,
            default: serde_json::json!(1000),
            min: Some(150.0),
            max: Some(2000.0),
            step: Some(2.0),
            options: Vec::new(),
            implemented: true,
            milestone: "04".into(),
        },
        ParameterDefinition {
            id: "glitch.glitch_size".into(),
            legacy_id: "glitchSize".into(),
            label: "GLITCH SIZE".into(),
            group: "Glitch".into(),
            kind: ParameterKind::Number,
            default: serde_json::json!(10),
            min: Some(1.0),
            max: Some(60.0),
            step: Some(0.01),
            options: Vec::new(),
            implemented: true,
            milestone: "04".into(),
        },
        ParameterDefinition {
            id: "glitch.glitch_alpha".into(),
            legacy_id: "glitchAlpha".into(),
            label: "GLITCH ALPHA".into(),
            group: "Glitch".into(),
            kind: ParameterKind::Number,
            default: serde_json::json!(1),
            min: Some(0.0),
            max: Some(1.0),
            step: Some(0.01),
            options: Vec::new(),
            implemented: true,
            milestone: "03".into(),
        },
        ParameterDefinition {
            id: "glitch.glitch_jitter".into(),
            legacy_id: "glitchJitter".into(),
            label: "GLITCH JITTER".into(),
            group: "Glitch".into(),
            kind: ParameterKind::Number,
            default: serde_json::json!(1),
            min: Some(0.0),
            max: Some(1.0),
            step: Some(0.01),
            options: Vec::new(),
            implemented: true,
            milestone: "04".into(),
        },
        ParameterDefinition {
            id: "glitch.glitch_smear".into(),
            legacy_id: "glitchSmear".into(),
            label: "GLITCH SMEAR".into(),
            group: "Glitch".into(),
            kind: ParameterKind::Number,
            default: serde_json::json!(6),
            min: Some(0.0),
            max: Some(200.0),
            step: Some(0.01),
            options: Vec::new(),
            implemented: true,
            milestone: "04".into(),
        },
        ParameterDefinition {
            id: "glitch.glitch_smear_angle".into(),
            legacy_id: "glitchSmearAngle".into(),
            label: "GLITCH SMEAR ANGLE".into(),
            group: "Glitch".into(),
            kind: ParameterKind::Number,
            default: serde_json::json!(0),
            min: Some(0.0),
            max: Some(360.0),
            step: Some(1.0),
            options: Vec::new(),
            implemented: true,
            milestone: "04".into(),
        },
        ParameterDefinition {
            id: "glitch.glitch_speed".into(),
            legacy_id: "glitchSpeed".into(),
            label: "GLITCH SPEED".into(),
            group: "Glitch".into(),
            kind: ParameterKind::Number,
            default: serde_json::json!(0.8),
            min: Some(0.0),
            max: Some(5.0),
            step: Some(0.005),
            options: Vec::new(),
            implemented: true,
            milestone: "04".into(),
        },
        ParameterDefinition {
            id: "glitch.glitch_speed_fine".into(),
            legacy_id: "glitchSpeedFine".into(),
            label: "GLITCH SPEED FINE".into(),
            group: "Glitch".into(),
            kind: ParameterKind::Number,
            default: serde_json::json!(1),
            min: Some(0.0),
            max: Some(10.0),
            step: Some(0.001),
            options: Vec::new(),
            implemented: true,
            milestone: "04".into(),
        },
        ParameterDefinition {
            id: "glitch.glitch_speed_mul".into(),
            legacy_id: "glitchSpeedMul".into(),
            label: "GLITCH SPEED MUL".into(),
            group: "Glitch".into(),
            kind: ParameterKind::Number,
            default: serde_json::json!(1),
            min: Some(0.0),
            max: Some(10.0),
            step: Some(0.1),
            options: Vec::new(),
            implemented: true,
            milestone: "04".into(),
        },
        ParameterDefinition {
            id: "glitch.glitch_base_x".into(),
            legacy_id: "glitchBaseX".into(),
            label: "GLITCH BASE X".into(),
            group: "Glitch".into(),
            kind: ParameterKind::Number,
            default: serde_json::json!(0),
            min: Some(-1000.0),
            max: Some(1000.0),
            step: Some(1.0),
            options: Vec::new(),
            implemented: true,
            milestone: "04".into(),
        },
        ParameterDefinition {
            id: "glitch.glitch_base_y".into(),
            legacy_id: "glitchBaseY".into(),
            label: "GLITCH BASE Y".into(),
            group: "Glitch".into(),
            kind: ParameterKind::Number,
            default: serde_json::json!(0),
            min: Some(-1000.0),
            max: Some(1000.0),
            step: Some(1.0),
            options: Vec::new(),
            implemented: true,
            milestone: "04".into(),
        },
        ParameterDefinition {
            id: "clusters.cluster_tiles".into(),
            legacy_id: "clusterTiles".into(),
            label: "CLUSTER TILES".into(),
            group: "Clusters".into(),
            kind: ParameterKind::Bool,
            default: serde_json::Value::Bool(false),
            min: None,
            max: None,
            step: None,
            options: Vec::new(),
            implemented: true,
            milestone: "05".into(),
        },
        ParameterDefinition {
            id: "clusters.clu_centers".into(),
            legacy_id: "cluCenters".into(),
            label: "CLU CENTERS".into(),
            group: "Clusters".into(),
            kind: ParameterKind::Number,
            default: serde_json::json!(3),
            min: Some(1.0),
            max: Some(20.0),
            step: Some(1.0),
            options: Vec::new(),
            implemented: true,
            milestone: "05".into(),
        },
        ParameterDefinition {
            id: "clusters.clu_spread".into(),
            legacy_id: "cluSpread".into(),
            label: "CLU SPREAD".into(),
            group: "Clusters".into(),
            kind: ParameterKind::Number,
            default: serde_json::json!(80),
            min: Some(1.0),
            max: Some(300.0),
            step: Some(1.0),
            options: Vec::new(),
            implemented: true,
            milestone: "05".into(),
        },
        ParameterDefinition {
            id: "clusters.clu_min_spread".into(),
            legacy_id: "cluMinSpread".into(),
            label: "CLU MIN SPREAD".into(),
            group: "Clusters".into(),
            kind: ParameterKind::Number,
            default: serde_json::json!(0),
            min: Some(0.0),
            max: Some(150.0),
            step: Some(1.0),
            options: Vec::new(),
            implemented: true,
            milestone: "05".into(),
        },
        ParameterDefinition {
            id: "clusters.spatial_gap".into(),
            legacy_id: "spatialGap".into(),
            label: "SPATIAL GAP".into(),
            group: "Clusters".into(),
            kind: ParameterKind::Number,
            default: serde_json::json!(40),
            min: Some(0.0),
            max: Some(200.0),
            step: Some(1.0),
            options: Vec::new(),
            // Despite its UI placement, original applyGlitch() uses SPATIAL GAP
            // for normal tile placement even when cluster tiling is disabled.
            implemented: true,
            milestone: "04.1".into(),
        },
        ParameterDefinition {
            id: "clusters.clu_bias".into(),
            legacy_id: "cluBias".into(),
            label: "CLU BIAS".into(),
            group: "Clusters".into(),
            kind: ParameterKind::Number,
            default: serde_json::json!(0.85),
            min: Some(0.0),
            max: Some(1.0),
            step: Some(0.01),
            options: Vec::new(),
            implemented: true,
            milestone: "05".into(),
        },
        ParameterDefinition {
            id: "clusters.clu_drift".into(),
            legacy_id: "cluDrift".into(),
            label: "CLU DRIFT".into(),
            group: "Clusters".into(),
            kind: ParameterKind::Number,
            default: serde_json::json!(0),
            min: Some(0.0),
            max: Some(5.0),
            step: Some(0.01),
            options: Vec::new(),
            implemented: true,
            milestone: "05".into(),
        },
        ParameterDefinition {
            id: "clusters.clu_speed".into(),
            legacy_id: "cluSpeed".into(),
            label: "CLU SPEED".into(),
            group: "Clusters".into(),
            kind: ParameterKind::Number,
            default: serde_json::json!(0),
            min: Some(0.0),
            max: Some(10.0),
            step: Some(0.01),
            options: Vec::new(),
            implemented: true,
            milestone: "05".into(),
        },
        ParameterDefinition {
            id: "clusters.clu_steer".into(),
            legacy_id: "cluSteer".into(),
            label: "CLU STEER".into(),
            group: "Clusters".into(),
            kind: ParameterKind::Number,
            default: serde_json::json!(1),
            min: Some(0.0),
            max: Some(10.0),
            step: Some(0.01),
            options: Vec::new(),
            implemented: true,
            milestone: "05".into(),
        },
        ParameterDefinition {
            id: "clusters.clu_speed_var".into(),
            legacy_id: "cluSpeedVar".into(),
            label: "CLU SPEED VAR".into(),
            group: "Clusters".into(),
            kind: ParameterKind::Number,
            default: serde_json::json!(0),
            min: Some(0.0),
            max: Some(2.0),
            step: Some(0.01),
            options: Vec::new(),
            implemented: true,
            milestone: "05".into(),
        },
        ParameterDefinition {
            id: "clusters.clu_pulse".into(),
            legacy_id: "cluPulse".into(),
            label: "CLU PULSE".into(),
            group: "Clusters".into(),
            kind: ParameterKind::Number,
            default: serde_json::json!(0),
            min: Some(0.0),
            max: Some(10.0),
            step: Some(0.1),
            options: Vec::new(),
            implemented: true,
            milestone: "05".into(),
        },
        ParameterDefinition {
            id: "clusters.clu_inertia".into(),
            legacy_id: "cluInertia".into(),
            label: "CLU INERTIA".into(),
            group: "Clusters".into(),
            kind: ParameterKind::Number,
            default: serde_json::json!(0.92),
            min: Some(0.01),
            max: Some(0.99),
            step: Some(0.01),
            options: Vec::new(),
            implemented: true,
            milestone: "05".into(),
        },
        ParameterDefinition {
            id: "clusters.clu_cohere".into(),
            legacy_id: "cluCohere".into(),
            label: "CLU COHERE".into(),
            group: "Clusters".into(),
            kind: ParameterKind::Number,
            default: serde_json::json!(0.8),
            min: Some(0.0),
            max: Some(1.0),
            step: Some(0.01),
            options: Vec::new(),
            implemented: true,
            milestone: "05".into(),
        },
        ParameterDefinition {
            id: "clusters.clu_breathe".into(),
            legacy_id: "cluBreathe".into(),
            label: "CLU BREATHE".into(),
            group: "Clusters".into(),
            kind: ParameterKind::Number,
            default: serde_json::json!(0),
            min: Some(0.0),
            max: Some(0.9),
            step: Some(0.01),
            options: Vec::new(),
            implemented: true,
            milestone: "05".into(),
        },
        ParameterDefinition {
            id: "clusters.clu_bounds".into(),
            legacy_id: "cluBounds".into(),
            label: "CLU BOUNDS".into(),
            group: "Clusters".into(),
            kind: ParameterKind::Select,
            default: serde_json::Value::String("bounce".into()),
            min: None,
            max: None,
            step: None,
            options: vec!["bounce".into(), "wrap".into()],
            implemented: true,
            milestone: "05".into(),
        },
        ParameterDefinition {
            id: "layers.layer_priority".into(),
            legacy_id: "layerPriority".into(),
            label: "LAYER PRIORITY".into(),
            group: "Layer Priority".into(),
            kind: ParameterKind::Select,
            default: serde_json::Value::String("scan".into()),
            min: None,
            max: None,
            step: None,
            options: vec!["scan".into(), "glitch".into(), "neutral".into(), "pulse".into()],
            implemented: true,
            milestone: "06".into(),
        },
        ParameterDefinition {
            id: "layers.layer_pulse_speed".into(),
            legacy_id: "layerPulseSpeed".into(),
            label: "LAYER PULSE SPEED".into(),
            group: "Layer Priority".into(),
            kind: ParameterKind::Number,
            default: serde_json::json!(2),
            min: Some(0.2),
            max: Some(12.0),
            step: Some(0.1),
            options: Vec::new(),
            implemented: true,
            milestone: "06".into(),
        },
        ParameterDefinition {
            id: "smoosh.smoosh_on".into(),
            legacy_id: "smooshOn".into(),
            label: "SMOOSH ON".into(),
            group: "Smoosh".into(),
            kind: ParameterKind::Bool,
            default: serde_json::Value::Bool(false),
            min: None,
            max: None,
            step: None,
            options: Vec::new(),
            implemented: true,
            milestone: "07".into(),
        },
        ParameterDefinition {
            id: "smoosh.smoosh_blend".into(),
            legacy_id: "smooshBlend".into(),
            label: "SMOOSH BLEND".into(),
            group: "Smoosh".into(),
            kind: ParameterKind::Select,
            default: serde_json::Value::String("screen".into()),
            min: None,
            max: None,
            step: None,
            options: vec!["screen".into(), "lighter".into(), "lighten".into(), "color-dodge".into(), "multiply".into(), "darken".into(), "color-burn".into(), "overlay".into(), "soft-light".into(), "hard-light".into(), "difference".into(), "exclusion".into(), "hue".into(), "saturation".into(), "color".into(), "luminosity".into()],
            implemented: true,
            milestone: "07".into(),
        },
        ParameterDefinition {
            id: "smoosh.smoosh_amt".into(),
            legacy_id: "smooshAmt".into(),
            label: "SMOOSH AMT".into(),
            group: "Smoosh".into(),
            kind: ParameterKind::Number,
            default: serde_json::json!(1),
            min: Some(0.0),
            max: Some(1.0),
            step: Some(0.01),
            options: Vec::new(),
            implemented: true,
            milestone: "07".into(),
        },
        ParameterDefinition {
            id: "smoosh.smoosh_invert".into(),
            legacy_id: "smooshInvert".into(),
            label: "SMOOSH INVERT".into(),
            group: "Smoosh".into(),
            kind: ParameterKind::Bool,
            default: serde_json::Value::Bool(false),
            min: None,
            max: None,
            step: None,
            options: Vec::new(),
            implemented: true,
            milestone: "07".into(),
        },
        ParameterDefinition {
            id: "luma.luma_key_on".into(),
            legacy_id: "lumaKeyOn".into(),
            label: "LUMA KEY ON".into(),
            group: "Luma Key".into(),
            kind: ParameterKind::Bool,
            default: serde_json::Value::Bool(false),
            min: None,
            max: None,
            step: None,
            options: Vec::new(),
            implemented: true,
            milestone: "07".into(),
        },
        ParameterDefinition {
            id: "luma.luma_key_ab".into(),
            legacy_id: "lumaKeyAB".into(),
            label: "LUMA KEY AB".into(),
            group: "Luma Key".into(),
            kind: ParameterKind::Number,
            default: serde_json::json!(0.5),
            min: Some(0.0),
            max: Some(1.0),
            step: Some(0.01),
            options: Vec::new(),
            implemented: true,
            milestone: "07".into(),
        },
        ParameterDefinition {
            id: "luma.luma_key_mix".into(),
            legacy_id: "lumaKeyMix".into(),
            label: "LUMA KEY MIX".into(),
            group: "Luma Key".into(),
            kind: ParameterKind::Number,
            default: serde_json::json!(0),
            min: Some(0.0),
            max: Some(1.0),
            step: Some(0.01),
            options: Vec::new(),
            implemented: true,
            milestone: "07".into(),
        },
        ParameterDefinition {
            id: "luma.luma_key_invert".into(),
            legacy_id: "lumaKeyInvert".into(),
            label: "LUMA KEY INVERT".into(),
            group: "Luma Key".into(),
            kind: ParameterKind::Bool,
            default: serde_json::Value::Bool(false),
            min: None,
            max: None,
            step: None,
            options: Vec::new(),
            implemented: true,
            milestone: "07".into(),
        },
        ParameterDefinition {
            id: "scanlines.clusters".into(),
            legacy_id: "clusters".into(),
            label: "CLUSTERS".into(),
            group: "Scanlines".into(),
            kind: ParameterKind::Bool,
            default: serde_json::Value::Bool(false),
            min: None,
            max: None,
            step: None,
            options: Vec::new(),
            implemented: true,
            milestone: "06".into(),
        },
        ParameterDefinition {
            id: "scanlines.scan_angle".into(),
            legacy_id: "scanAngle".into(),
            label: "SCAN ANGLE".into(),
            group: "Scanlines".into(),
            kind: ParameterKind::Number,
            default: serde_json::json!(0),
            min: Some(-180.0),
            max: Some(180.0),
            step: Some(1.0),
            options: Vec::new(),
            implemented: true,
            milestone: "06".into(),
        },
        ParameterDefinition {
            id: "scanlines.scan_spin_left".into(),
            legacy_id: "scanSpinLeft".into(),
            label: "SCAN SPIN LEFT".into(),
            group: "Scanlines".into(),
            kind: ParameterKind::Bool,
            default: serde_json::Value::Bool(false),
            min: None,
            max: None,
            step: None,
            options: Vec::new(),
            implemented: true,
            milestone: "06".into(),
        },
        ParameterDefinition {
            id: "scanlines.scan_spin_right".into(),
            legacy_id: "scanSpinRight".into(),
            label: "SCAN SPIN RIGHT".into(),
            group: "Scanlines".into(),
            kind: ParameterKind::Bool,
            default: serde_json::Value::Bool(false),
            min: None,
            max: None,
            step: None,
            options: Vec::new(),
            implemented: true,
            milestone: "06".into(),
        },
        ParameterDefinition {
            id: "scanlines.scan_spin_speed".into(),
            legacy_id: "scanSpinSpeed".into(),
            label: "SCAN SPIN SPEED".into(),
            group: "Scanlines".into(),
            kind: ParameterKind::Number,
            default: serde_json::json!(1),
            min: Some(0.1),
            max: Some(10.0),
            step: Some(0.1),
            options: Vec::new(),
            implemented: true,
            milestone: "06".into(),
        },
        ParameterDefinition {
            id: "scanlines.cluster_count".into(),
            legacy_id: "clusterCount".into(),
            label: "CLUSTER COUNT".into(),
            group: "Scanlines".into(),
            kind: ParameterKind::Number,
            default: serde_json::json!(3),
            min: Some(1.0),
            max: Some(50.0),
            step: Some(1.0),
            options: Vec::new(),
            implemented: true,
            milestone: "06".into(),
        },
        ParameterDefinition {
            id: "scanlines.cluster_radius".into(),
            legacy_id: "clusterRadius".into(),
            label: "CLUSTER RADIUS".into(),
            group: "Scanlines".into(),
            kind: ParameterKind::Number,
            default: serde_json::json!(10),
            min: Some(1.0),
            max: Some(120.0),
            step: Some(1.0),
            options: Vec::new(),
            implemented: true,
            milestone: "06".into(),
        },
        ParameterDefinition {
            id: "scanlines.scan_focus".into(),
            legacy_id: "scanFocus".into(),
            label: "SCAN FOCUS".into(),
            group: "Scanlines".into(),
            kind: ParameterKind::Number,
            default: serde_json::json!(0.5),
            min: Some(0.0),
            max: Some(2.0),
            step: Some(0.01),
            options: Vec::new(),
            implemented: true,
            milestone: "06".into(),
        },
        ParameterDefinition {
            id: "scanlines.scan_shift".into(),
            legacy_id: "scanShift".into(),
            label: "SCAN SHIFT".into(),
            group: "Scanlines".into(),
            kind: ParameterKind::Number,
            default: serde_json::json!(0.12),
            min: Some(-4.0),
            max: Some(4.0),
            step: Some(0.01),
            options: Vec::new(),
            implemented: true,
            milestone: "06".into(),
        },
        ParameterDefinition {
            id: "scanlines.scan_skew".into(),
            legacy_id: "scanSkew".into(),
            label: "SCAN SKEW".into(),
            group: "Scanlines".into(),
            kind: ParameterKind::Number,
            default: serde_json::json!(0),
            min: Some(-3.0),
            max: Some(3.0),
            step: Some(0.01),
            options: Vec::new(),
            implemented: true,
            milestone: "06".into(),
        },
        ParameterDefinition {
            id: "scanlines.scan_drift".into(),
            legacy_id: "scanDrift".into(),
            label: "SCAN DRIFT".into(),
            group: "Scanlines".into(),
            kind: ParameterKind::Number,
            default: serde_json::json!(0.5),
            min: Some(0.0),
            max: Some(5.0),
            step: Some(0.01),
            options: Vec::new(),
            implemented: true,
            milestone: "06".into(),
        },
        ParameterDefinition {
            id: "scanlines.scan_place_x".into(),
            legacy_id: "scanPlaceX".into(),
            label: "SCAN PLACE X".into(),
            group: "Scanlines".into(),
            kind: ParameterKind::Number,
            default: serde_json::json!(0),
            min: Some(-1.0),
            max: Some(1.0),
            step: Some(0.01),
            options: Vec::new(),
            implemented: true,
            milestone: "06".into(),
        },
        ParameterDefinition {
            id: "scanlines.scan_place_y".into(),
            legacy_id: "scanPlaceY".into(),
            label: "SCAN PLACE Y".into(),
            group: "Scanlines".into(),
            kind: ParameterKind::Number,
            default: serde_json::json!(0),
            min: Some(-1.0),
            max: Some(1.0),
            step: Some(0.01),
            options: Vec::new(),
            implemented: true,
            milestone: "06".into(),
        },
        ParameterDefinition {
            id: "scanlines.scan_zoom".into(),
            legacy_id: "scanZoom".into(),
            label: "SCAN ZOOM".into(),
            group: "Scanlines".into(),
            kind: ParameterKind::Number,
            default: serde_json::json!(1),
            min: Some(0.25),
            max: Some(6.0),
            step: Some(0.01),
            options: Vec::new(),
            implemented: true,
            milestone: "06".into(),
        },
        ParameterDefinition {
            id: "scanlines.scan_zoom_mode".into(),
            legacy_id: "scanZoomMode".into(),
            label: "SCAN ZOOM MODE".into(),
            group: "Scanlines".into(),
            kind: ParameterKind::Select,
            default: serde_json::Value::String("content".into()),
            min: None,
            max: None,
            step: None,
            options: vec!["content".into(), "pattern".into(), "both".into()],
            implemented: true,
            milestone: "06".into(),
        },
        ParameterDefinition {
            id: "scanlines.scan_speed".into(),
            legacy_id: "scanSpeed".into(),
            label: "SCAN SPEED".into(),
            group: "Scanlines".into(),
            kind: ParameterKind::Number,
            default: serde_json::json!(1),
            min: Some(0.0),
            max: Some(5.0),
            step: Some(0.01),
            options: Vec::new(),
            implemented: true,
            milestone: "06".into(),
        },
        ParameterDefinition {
            id: "scanlines.scan_gap".into(),
            legacy_id: "scanGap".into(),
            label: "SCAN GAP".into(),
            group: "Scanlines".into(),
            kind: ParameterKind::Number,
            default: serde_json::json!(0),
            min: Some(0.0),
            max: Some(200.0),
            step: Some(1.0),
            options: Vec::new(),
            implemented: true,
            milestone: "06".into(),
        },
        ParameterDefinition {
            id: "scanlines.scan_alpha".into(),
            legacy_id: "scanAlpha".into(),
            label: "SCAN ALPHA".into(),
            group: "Scanlines".into(),
            kind: ParameterKind::Number,
            default: serde_json::json!(0.86),
            min: Some(0.0),
            max: Some(1.0),
            step: Some(0.01),
            options: Vec::new(),
            implemented: true,
            milestone: "06".into(),
        },
        ParameterDefinition {
            id: "global_mix.global_mix_on".into(),
            legacy_id: "globalMixOn".into(),
            label: "GLOBAL MIX ON".into(),
            group: "Global Mix".into(),
            kind: ParameterKind::Bool,
            default: serde_json::Value::Bool(false),
            min: None,
            max: None,
            step: None,
            options: Vec::new(),
            implemented: true,
            milestone: "07".into(),
        },
        ParameterDefinition {
            id: "global_mix.global_mix_blend".into(),
            legacy_id: "globalMixBlend".into(),
            label: "GLOBAL MIX BLEND".into(),
            group: "Global Mix".into(),
            kind: ParameterKind::Select,
            default: serde_json::Value::String("screen".into()),
            min: None,
            max: None,
            step: None,
            options: vec!["screen".into(), "lighter".into(), "lighten".into(), "color-dodge".into(), "multiply".into(), "darken".into(), "color-burn".into(), "overlay".into(), "soft-light".into(), "hard-light".into(), "difference".into(), "exclusion".into(), "hue".into(), "saturation".into(), "color".into(), "luminosity".into(), "source-over".into()],
            implemented: true,
            milestone: "07".into(),
        },
        ParameterDefinition {
            id: "global_mix.global_mix_amt".into(),
            legacy_id: "globalMixAmt".into(),
            label: "GLOBAL MIX AMT".into(),
            group: "Global Mix".into(),
            kind: ParameterKind::Number,
            default: serde_json::json!(0),
            min: Some(0.0),
            max: Some(1.0),
            step: Some(0.01),
            options: Vec::new(),
            implemented: true,
            milestone: "07".into(),
        },
        ParameterDefinition {
            id: "global_mix.global_mix_pos".into(),
            legacy_id: "globalMixPos".into(),
            label: "GLOBAL MIX POS".into(),
            group: "Global Mix".into(),
            kind: ParameterKind::Select,
            default: serde_json::Value::String("after".into()),
            min: None,
            max: None,
            step: None,
            options: vec!["before".into(), "after".into(), "afterflow".into(), "final".into()],
            implemented: true,
            milestone: "07".into(),
        },
        ParameterDefinition {
            id: "flow.flow_on".into(),
            legacy_id: "flowOn".into(),
            label: "FLOW ON".into(),
            group: "Flow".into(),
            kind: ParameterKind::Bool,
            default: serde_json::Value::Bool(false),
            min: None,
            max: None,
            step: None,
            options: Vec::new(),
            implemented: true,
            milestone: "07".into(),
        },
        ParameterDefinition {
            id: "flow.flow_strength".into(),
            legacy_id: "flowStrength".into(),
            label: "FLOW STRENGTH".into(),
            group: "Flow".into(),
            kind: ParameterKind::Number,
            default: serde_json::json!(6),
            min: Some(0.0),
            max: Some(20.0),
            step: Some(1.0),
            options: Vec::new(),
            implemented: true,
            milestone: "07".into(),
        },
        ParameterDefinition {
            id: "flow.flow_scale".into(),
            legacy_id: "flowScale".into(),
            label: "FLOW SCALE".into(),
            group: "Flow".into(),
            kind: ParameterKind::Number,
            default: serde_json::json!(80),
            min: Some(40.0),
            max: Some(200.0),
            step: Some(1.0),
            options: Vec::new(),
            implemented: true,
            milestone: "07".into(),
        },
        ParameterDefinition {
            id: "flow.flow_speed".into(),
            legacy_id: "flowSpeed".into(),
            label: "FLOW SPEED".into(),
            group: "Flow".into(),
            kind: ParameterKind::Number,
            default: serde_json::json!(1),
            min: Some(0.0),
            max: Some(6.0),
            step: Some(0.01),
            options: Vec::new(),
            implemented: true,
            milestone: "07".into(),
        },
        ParameterDefinition {
            id: "flow.flow_pulse".into(),
            legacy_id: "flowPulse".into(),
            label: "FLOW PULSE".into(),
            group: "Flow".into(),
            kind: ParameterKind::Number,
            default: serde_json::json!(0),
            min: Some(0.0),
            max: Some(200.0),
            step: Some(1.0),
            options: Vec::new(),
            implemented: true,
            milestone: "07".into(),
        },
        ParameterDefinition {
            id: "flow.flow_pulse_trig".into(),
            legacy_id: "flowPulseTrig".into(),
            label: "FLOW PULSE TRIG".into(),
            group: "Flow".into(),
            kind: ParameterKind::Bool,
            default: serde_json::Value::Bool(false),
            min: None,
            max: None,
            step: None,
            options: Vec::new(),
            implemented: true,
            milestone: "07".into(),
        },
        ParameterDefinition {
            id: "flow.flow_impl".into(),
            legacy_id: "flowImpl".into(),
            label: "FLOW IMPL".into(),
            group: "Flow".into(),
            kind: ParameterKind::Number,
            default: serde_json::json!(0),
            min: Some(-5.0),
            max: Some(5.0),
            step: Some(0.01),
            options: Vec::new(),
            implemented: true,
            milestone: "07".into(),
        },
        ParameterDefinition {
            id: "flow.flow_swirl".into(),
            legacy_id: "flowSwirl".into(),
            label: "FLOW SWIRL".into(),
            group: "Flow".into(),
            kind: ParameterKind::Number,
            default: serde_json::json!(0),
            min: Some(-2.0),
            max: Some(2.0),
            step: Some(0.01),
            options: Vec::new(),
            implemented: true,
            milestone: "07".into(),
        },
        ParameterDefinition {
            id: "flow.flow_turb".into(),
            legacy_id: "flowTurb".into(),
            label: "FLOW TURB".into(),
            group: "Flow".into(),
            kind: ParameterKind::Number,
            default: serde_json::json!(0),
            min: Some(0.0),
            max: Some(1.0),
            step: Some(0.01),
            options: Vec::new(),
            implemented: true,
            milestone: "07".into(),
        },
        ParameterDefinition {
            id: "flow.flow_spread".into(),
            legacy_id: "flowSpread".into(),
            label: "FLOW SPREAD".into(),
            group: "Flow".into(),
            kind: ParameterKind::Number,
            default: serde_json::json!(1),
            min: Some(0.25),
            max: Some(4.0),
            step: Some(0.01),
            options: Vec::new(),
            implemented: true,
            milestone: "07".into(),
        },
        ParameterDefinition {
            id: "flow.flow_carry".into(),
            legacy_id: "flowCarry".into(),
            label: "FLOW CARRY".into(),
            group: "Flow".into(),
            kind: ParameterKind::Number,
            default: serde_json::json!(0),
            min: Some(0.0),
            max: Some(2.0),
            step: Some(0.01),
            options: Vec::new(),
            implemented: true,
            milestone: "07".into(),
        },
        ParameterDefinition {
            id: "flow.flow_target".into(),
            legacy_id: "flowTarget".into(),
            label: "FLOW TARGET".into(),
            group: "Flow".into(),
            kind: ParameterKind::Select,
            default: serde_json::Value::String("final".into()),
            min: None,
            max: None,
            step: None,
            options: vec!["final".into(), "glitch".into(), "scan".into()],
            implemented: true,
            milestone: "07".into(),
        }
    ])
}
